### ISSUE TITLE
Tainted Magic Version 1.1.6.3 said it is out of date. Using Version 1.1.6.2

### ISSUE THREAD

**Issue by Dream-Master** [yorkeJohn/Tainted-Magic#1]
I installed Version 1.1.6.3 but every time i join the Game I see this warning.
![screenshot 2015-11-22 13 07 44](https://cloud.githubusercontent.com/assets/2970688/11323703/46779b78-911a-11e5-9edc-c862ba74e71d.png)

**Comment by yorkeJohn** [comment]
Updated latest version file.

**Comment by Dream-Master** [comment]
You mean 1.1.6.4?
