### ISSUE TITLE
Eldritch Focus projectile wierdness

### ISSUE THREAD

**Issue by Shahelion** [yorkeJohn/Tainted-Magic#10]
The focus seems to be slightly above the trail it creates, also the trail seems to be the wrong color. I recall the trail used to be properly dark in a past version...

https://i.gyazo.com/dc420e32134df38373c27b24f07cbde2.mp4

**Comment by yorkeJohn** [comment]
Oh my, I was testing particles and I do remember setting this to happen. Looks like I never changed it back... :L
