### ISSUE TITLE
Warped Eye only works with Perditio

### ISSUE THREAD

**Issue by Shahelion** [yorkeJohn/Tainted-Magic#11]
No matter where I look when holding it, I can only ever use the Perditio aspect symbol.

![2015-11-29_10 57 17](https://cloud.githubusercontent.com/assets/6917535/11459291/2b06bdba-9688-11e5-8f59-5880931fd114.png)

**Comment by yorkeJohn** [comment]
I had this bug when I was programming the eye, but I proceeded to fix it. It seems it is back. More info please?

**Comment by Shahelion** [comment]
No matter which direction I face while holding it, it only shows the Perditio one. I am unable to bind locations to the other 5 aspects. It's like it only has the one.

**Comment by Shahelion** [comment]
Did you ever figure out the problem with this?

**Comment by yorkeJohn** [comment]
No, sorry, I will be debugging in the near future. I will keep you updated if this I find anything on the issue. Since it seems that is just you it could be another mod conflicting.

**Comment by Shadows-of-Fire** [comment]
Yorke, are you back to developing TM?  
If  you are, are you going to move to 1.8 or continue on 1.7?

**Comment by yorkeJohn** [comment]
Just debugging and tweaking a few things for balance before setting down the mod. I do not think I will update to 1.8, I just don't have the time or the interest to learn 1.8 modding yet. Though, I am working on something else ;) keep tuned!
