### ISSUE TITLE
Crafting a Thaumcraft Iron Caped one (the first one) Crash the Game

### ISSUE THREAD

**Issue by Dream-Master** [yorkeJohn/Tainted-Magic#12]
When i try to lay a Thaumcraft Iron Capped Wand in the Inventory the Game crash.

Tested with Tainted magic 1.6.4

Client Crash:
https://gist.github.com/Dream-Master/8a8b011a46f6ed1ec843#file-tainted-magic

Sever Error:

https://gist.github.com/Dream-Master/5a2bec01e41a161e2b16#file-ultrapeeks

Post it here too:

https://github.com/micdoodle8/Galacticraft/issues/1955

**Comment by Dream-Master** [comment]
@yorkeJohn 

Look what one of my players find out.

https://github.com/GTNewHorizons/NewHorizons/issues/412

**Comment by yorkeJohn** [comment]
Potentially fixed for the next version, will be in next patch.

**Comment by Dream-Master** [comment]
Thanks
