### ISSUE TITLE
Voidwalker's Sash of Runic Sheilding has incorrect sheilding amount

### ISSUE THREAD

**Issue by jnk1136** [yorkeJohn/Tainted-Magic#14]
The Thaumonomicon claims the Sash is supposed to give +20 Runic Sheilding, but the tooltip for the item reveals that it has only +15. Not sure if this is an issue with the item or the Thaumonomicon entry, but my two cents is that +20 seems a bit more balanced, considering the associated cost of crafting the item. For a paltry +5 over the Girdle of Runic Shielding, I'm not sure I'd bother making the Sash when I could make the Kinetic Girdle instead.

**Comment by yorkeJohn** [comment]
Oops. An issue with the sash. I don't know why it would be 15 though, I probably changed it for testing reasons and never fixed it.
