### ISSUE TITLE
Invalid JSON (mcmod.info) in latest version

### ISSUE THREAD

**Issue by srs-bsns** [yorkeJohn/Tainted-Magic#15]
[Client thread/ERROR] [FML/]: The mcmod.info file in TaintedMagic-1.1.6.4.jar cannot be parsed as valid JSON. It will be ignored
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 7 column 5

`"version": "1.1.6.4,`

Missing a quotation mark. I assume it was deleted accidentally when it was updated. :)

**Comment by yorkeJohn** [comment]
It souldn't've been. I can use the mod fine. I will check though.

**Comment by yorkeJohn** [comment]
Oh, it is missing a quotation. Will fix :)
