### ISSUE TITLE
[Suggestion] thaumic elite smelting factory

### ISSUE THREAD

**Issue by Renegade2** [yorkeJohn/Tainted-Magic#22]
the infernal furnace feels a little underpowered to me,this mod could use a thaumic version of mekanism's elite smelting factory.made using 4 thaumic alloy,2 primordial orbs(not consumed) 4 void metal 4 shadow metal and 2 nether stars infused into the elite smelting factory.speed upgrades need to be combined with 4 thaumic alloy to make a thaumic speed upgrade.energy upgrades need to be combined with 4 thaumic alloy to make 1 thaumic vis upgrade.works like energy,but reduces the vis cost instead.operation requires 5 ignis and 5 terra essentia each operation (every time a item enters a slot).

**Comment by yorkeJohn** [comment]
This is a bug tracker, not a suggestion box. Head over to the forums if you have suggestions :)

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2437825-tainted-magic-1-1-6-4-a-thaumcraft-addon
