### ISSUE TITLE
Crimson Robes and Crimson Cloth Caps recipe issue

### ISSUE THREAD

**Issue by Dayyer1** [yorkeJohn/Tainted-Magic#23]
^ see title for bug description. I posted on the forum thread, and forgot about the bug tracker. Sorry.

**Comment by Dayyer1** [comment]
The Crimson Robes Hood, I think it is (can't search it at the moment, my computer is lagging to death) and the Crimson Cloth Caps have the same recipe.

**Comment by yorkeJohn** [comment]
Resolved. thanks for pointing this out!
