### ISSUE TITLE
TM tab not appearing in thaumcraft book

### ISSUE THREAD

**Issue by thorpey9490** [yorkeJohn/Tainted-Magic#25]
for some reason the tainted magic tab is not appearing in my thaumcraft book ?

**Comment by Shadows-of-Fire** [comment]
This question lacks information.  Did you perhaps overload the Thaumonomicon, causing it to not display any extra tabs?  If so, go install http://minecraft.curseforge.com/projects/notenoughthaumcrafttabs  
I am certain that Tainted Magic's Tab displays correctly.

**Comment by yorkeJohn** [comment]
Yeah, most likely just an overloaded Thaumonomicon. Check that you don't have too many addons installed!

**Comment by Shadows-of-Fire** [comment]
There's also a nice addon that allows for extra tab slots if that is the actual issue.

**Comment by yorkeJohn** [comment]
Yes, I do recommend Not Enough Thaumcraft Tabs.
