### ISSUE TITLE
[Suggestion] Config to disable items

### ISSUE THREAD

**Issue by Eufranio** [yorkeJohn/Tainted-Magic#26]
Would be nice a config to disable the items on ItemRegistry in the forge startup, similar how ExtraUtilities, Draconic Evolution, does.

**Comment by yorkeJohn** [comment]
This is a bug tracker, not a suggestion box. Head over to the forums if you have suggestions :)

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2437825-tainted-magic-1-1-6-4-a-thaumcraft-addon

**Comment by Eufranio** [comment]
Forums are confusing, why not allow us to post them here? Use the forum for feedback reasons only?
. _.

**Comment by yorkeJohn** [comment]
Because this is a Bug Tracker... The forums are for suggestions and feedback. Bugs are technical issues, thus I like to track them on GitHub. The forums are good for suggestions because people can discuss the mod, suggest and give feedback.
