### ISSUE TITLE
Error when using r7.0 build on server

### ISSUE THREAD

**Issue by Luckyday84** [yorkeJohn/Tainted-Magic#27]
When I updated to the lastest version I get the error in the pastebin on server startup.

Im using forge 10.13.4.1614

http://pastebin.com/VzTNhXRu

Let me know if you need me to provide any other info.

**Comment by yorkeJohn** [comment]
When did the crash happen?

**Comment by Luckyday84** [comment]
It crashes right when I run the script to start the Minecraft server.

**Comment by Shadows-of-Fire** [comment]
Yorke stop trying to call client render on the server

**Comment by yorkeJohn** [comment]
Yeah I just forgot to @sideonly some render code. I'll fix that ASAP.

**Comment by yorkeJohn** [comment]
Fixed.
