### ISSUE TITLE
[Minor] Capitalization

### ISSUE THREAD

**Issue by Shahelion** [yorkeJohn/Tainted-Magic#28]
The n in "Mode: normal" isn't capitalized. Haven't made one yet, so can't check other modes.

Just a little something that was bugging me.

![2016-10-26_15 21 42](https://cloud.githubusercontent.com/assets/6917535/19747429/7f72528e-9b90-11e6-92e1-0819e710dffd.png)

**Comment by yorkeJohn** [comment]
Fixed
