### ISSUE TITLE
Ticking Memory Connection Crash

### ISSUE THREAD

**Issue by StarVYT** [yorkeJohn/Tainted-Magic#29]
Hello. Whenever I try to load this mod on a world in my custom modpack, Arctic Arrival, it seems to crash as I load it. It only appears to happen on r7.0 and up. 1.1.6.4 worked fine. I think it may be an incompatibility with my custom mod, but that is highly unlikely. Note that I don't see anything relating to Tainted Magic in the log, but it only happens with the updated version.

Crash Report: http://pastebin.com/u1smzWgS

Log (The log was too big (4.65 MB), so I uploaded it to Dropbox): https://dl.dropboxusercontent.com/s/9493s6nonkb25ur/fml-client-latest.log

**Comment by yorkeJohn** [comment]
Did this crash happen immediately after logging into an existing world with tainted magic after updating? Did you try logging into a brand new world?

**Comment by StarVYT** [comment]
It happened on both an existing world and a new world. Reverting to the old version also fixed the issue after the crash on an existing world that crashed as well.

**Comment by Armigus** [comment]
It's related to the warpwood wand/staff.  I had it in my inventory on load and I got a similar crash.  I put the staff into a bag and it loaded fine to start then crashed when I opened the bag.  Sadly I will have to destroy the nice staff to shift over.

I also noticed that the block and item names got reshuffled, nullifying all the custom John Smith textures I made for the mod.  That should require little more than reloading the images from the mod and renaming what I changed.

**Comment by StarVYT** [comment]
It happens on a newly generated world, too, so that might not be the problem, as I wouldn't have the wand at that time.

**Comment by yorkeJohn** [comment]
It should be just the wand causing this since the ID was changed.

**Comment by StarVYT** [comment]
I found the issue. It was actually Hardcore Questing Mode trying to load nonexistent items from the quest book file. Turns out it was nothing wrong with the mod, simply the renaming of items.
