### ISSUE TITLE
Arcane recipe error Mushroom Funguar

### ISSUE THREAD

**Issue by Dream-Master** [yorkeJohn/Tainted-Magic#33]
http://imgur.com/a/f7w5h

I guess it not cost 32767 air shards to make it. It's the wildcard value probably.

Version r7.3

https://github.com/yorkeJohn/Tainted-Magic/blob/d0c9d9fd806aed8e78213c5d6f42c7cd46fc0855/src/main/java/taintedmagic/common/lib/LibRecipes.java#L617

**Comment by Dream-Master** [comment]
Open it a second time the number on the Shard are gone????

**Comment by yorkeJohn** [comment]
Hmm interesting, ill try and fix this asap.

**Comment by yorkeJohn** [comment]
Ok. The problem was I set the stack size to 32767 instead of the metadata (wildcard value).
