### ISSUE TITLE
Tiny Lag

### ISSUE THREAD

**Issue by Dayyer1** [yorkeJohn/Tainted-Magic#36]
When I release a charged Stormbound Inscription on a Shadowmetal Fortress Blade, there's about a second of lag. The Tainted Inscription does not lag. I haven't tried the Volcanic Inscription.
The lag only lasts a second, but it could be annoying if you're trying to use it a lot, or in some sort of PVP setting.

**Comment by Dayyer1** [comment]
Oh yeah, I'm using version 7.5.

**Comment by yorkeJohn** [comment]
Ill take a look at this. I did some more testing and yeah, I'm getting a lag spike too.

**Comment by yorkeJohn** [comment]
This also happens with all three blades... Thaumium, Voidmetal, and Shadowmetal.

**Comment by yorkeJohn** [comment]
Closed due to inscriptions being redesigned.
