### ISSUE TITLE
[Suggestion] Warped Eye Penalties

### ISSUE THREAD

**Issue by Shahelion** [yorkeJohn/Tainted-Magic#37]
I understand that it was pretty powerful, but it was fun to use and it looked good. So why not have it simply apply a potion effect or two whenever used? Something like Slowness, or Mining Fatigue, or Weakness, or Nausea (or all 4).

Alternately, how about it also applies a hidden effect that causes negative effects to increment in strength (and maybe also duration) if the Eye is used to soon after the previous use. Something like 5-10 minutes would probably be reasonable, maybe with a config to make it longer if you're feeling particularly self-punishing.

Why is it that every time a mod makes an item like this, it ends up changing or removing it?

**Comment by yorkeJohn** [comment]
The off first please do NOT submit suggestions here. That's what the minecraft forums are for... there are a lot of reasons the warped eye was removed... you can make infinite of them, essentially being able to mark infinite locations. Also it was me re-implementing a TC version of the old eye of flügel that was removed from botania, so legal copyright break there. It's better that it stays removed until I redesign it.

**Comment by Shahelion** [comment]
Woops, yup sorry, forgot about not posting suggestions here.

Regarding making endless Eyes, why not make the locations player-specific? Would prevent sharing locations between players, but would also limit each player to one Eye's worth of marks.

Could always just ask Vazkii himself if it's ok you use the idea, after all, he did remove it.

**Comment by Shadows-of-Fire** [comment]
To be fair botania's license allows it
