### ISSUE TITLE
crash near specific player

### ISSUE THREAD

**Issue by ghoulsblade** [yorkeJohn/Tainted-Magic#38]
bizzmark often crashes when near noctambulant,
java.lang.NullPointerException: Ticking entity
    at taintedmagic.common.lib.handler.TMEventHandler.updateAttackDamage(TMEventHandler.java:112)
TaintedMagic-1.1.6.4.jar in GTNewHorizons pack
http://pastebin.com/mLauwhka
probably updateAttackDamage in TaintedMagicEventHandler.java
https://github.com/yorkeJohn/Tainted-Magic/blob/5042ef2df839ceb76ef7f32b06f3c61e8278921d/src/main/java/taintedmagic/common/handler/TaintedMagicEventHandler.java#L71

**Comment by yorkeJohn** [comment]
Update.

Current version is r7.5

This was fixed.
