### ISSUE TITLE
Boots of the Voidwalker don't display vis discount in tooltip

### ISSUE THREAD

**Issue by KryptonCaptain** [yorkeJohn/Tainted-Magic#39]
As above.

**Comment by yorkeJohn** [comment]
Oops.

**Comment by zHawky** [comment]
Can i write issue here?
So, in previous versions(i mean 2015 ver of tainted magic) Boots of Voidwalker have void particles, in 7.x versions that feature is dissapeared.. can you bring it back?

**Comment by yorkeJohn** [comment]
No. I removed it because it was buggy, laggy, and annoying.

**Comment by yorkeJohn** [comment]
Fixed.
