### ISSUE TITLE
Repair Enchants

### ISSUE THREAD

**Issue by 63502** [yorkeJohn/Tainted-Magic#4]
Are the shadowmetal tools and crystalline blade supposed to be able to receive the repair enchantment? Currently(v 1.1.6.4), none of the listed tools can be enchanted with repair. I don't know if this is a bug or not, but I saw a comment on curseforge about Dragonslayer having this issue with the Primal Blade of Corruption.

Also in reference to your reply to Dragonslayer's comment, could you possibly link this Github issue tracker on the top bar of the mod page? Other mod pages do this, and it makes it easier for anyone having issues to find the right place to post. 

Keep up the great work! :D 
     63502

**Comment by yorkeJohn** [comment]
Forgot to implement IRepairable. I will add the issue tracker to the top bar.
