### ISSUE TITLE
Wand Focus: Vis Shard ~ Casting Cost

### ISSUE THREAD

**Issue by Shahelion** [yorkeJohn/Tainted-Magic#40]
It seems that you forgot to adjust the cost to fit with TC4's system instead of TC5's. Right now it would take 100 Vis Shards just to use up a single point of Vis for each aspect used, and since mobs drop aspect orbs when killed, it might as well be free.

Maybe change it from 0.01 to 0.1 Vis per cast, I think that's around what the others use.

I was really fighting with my self whether I wanted to report this...hehe.

**Comment by yorkeJohn** [comment]
Thank you for reporting. Yeah I forgot that TC5 got rid of centi vis. I'll change that.

**Comment by yorkeJohn** [comment]
Fixed.
