### ISSUE TITLE
Primordial Pearl consumed when making Shadowmetal Caps

### ISSUE THREAD

**Issue by mjaw10** [yorkeJohn/Tainted-Magic#41]
The Primordial Pearl is consumed when making Shadowmetal Caps when the Thaumonomicon states it is not consumed when making them.

**Comment by yorkeJohn** [comment]
Ah yes they are supposed to be consumed, just didn't update the Thaumonomicon entry.

**Comment by yorkeJohn** [comment]
Fixed.
