### ISSUE TITLE
Fortress blade inscription fire/taint charge attack only does 1 point of damage to most mobs

### ISSUE THREAD

**Issue by LaughingSoul** [yorkeJohn/Tainted-Magic#44]
So I noticed after putting the taint inscription on my shadow fortress blade it only did 1 point of damage (not including poison). 

Fire was a bit different, the fireball seems to do more damage the farther away it lands from a mob. (max 5 damage if you hit them with the very edge of the explosion) but only 1 damage with a direct hit.
This isn't true when hitting ghasts as it insta kills them.

neither blade did melee damage at point blank with the charge up. im assuming this is a feature and not a bug since the thaumonomicon says to sneak if we want to do a regular hit.

**Comment by yorkeJohn** [comment]
Beefed up the damage... significantly.
