### ISSUE TITLE
Wand Focus: Vis Shard Projectile bouncing bugs.

### ISSUE THREAD

**Issue by 63502** [yorkeJohn/Tainted-Magic#45]
The shards fired from the vis shard focus do not bounce at the proper angles when they collide with blocks. They end up rebounding until they fade. This is really annoying, as it makes the focus nearly useless anywhere an enemy/target can go around a corner.

**Comment by 63502** [comment]
Your latest update is phenomenal other than this though. Well done. :D

**Comment by yorkeJohn** [comment]
Unfortunately the code that handles the vis shard's motion just wasn't designed with corners in mind. It's Azanor's code, not mine. I'll see what I can do to improve the tracking ability of the vis shard.

**Comment by 63502** [comment]
Closing due to TC6 release and inactivity.
