### ISSUE TITLE
Default Lumos focus gives fatal error if checked on while upgrading.

### ISSUE THREAD

**Issue by Archielotl** [yorkeJohn/Tainted-Magic#46]
If I open a focal manipulator while it is upgrading a default lumos focus (only frugal upgrades, no glow pet/lumos maxima), I am kicked out of my world with the message "A fatal error has occured, this connection is terminated." Once the focus is done upgrading, I can open the manipulator just fine, until I start upgrading again.

**Comment by yorkeJohn** [comment]
I believe it is because [I called a null if the focus is upgraded with neither the Glowpet or Maxima upgrades.](https://github.com/yorkeJohn/Tainted-Magic/blob/master/src/main/java/taintedmagic/common/items/wand/foci/ItemFocusLumos.java#L202-L209) I will fix this for the next patch.

**Comment by yorkeJohn** [comment]
Fixed.
