### ISSUE TITLE
Foci cooldown

### ISSUE THREAD

**Issue by Dayyer1** [yorkeJohn/Tainted-Magic#5]
I saw a post earlier about the foci cooldown acting funny, and after using the tainted blast foci, the cooldown carried over to all other wands/staves in my inventory. Right after using the tainted blast (sorry if that's the wrong name for it, not currently at my computer to check) I had to wait to use any other wand in my inventory until the tainted blast focus was ready again.

**Comment by 63502** [comment]
HEEEY!!! I saw you over on gadomancy!

Anyway, the cooldown carrying over to other foci on the same wand/staff thing is supposed to happen, it is not a bug

It does get annoying when 15+ sec cooldowns get involved though. :P

**Comment by Dayyer1** [comment]
Yes, I remember you!
I am currently on that last issue looking for the link to the programming...
PM me maybe on why the cooldown carries over, though. I don't want to fill up anybody's inbox with too many notifications... Although, here's one more!

**Comment by Dayyer1** [comment]
I just noticed there are no pm's... Nvm...

**Comment by Shahelion** [comment]
Doesn't really seem like something that's supposed to happen, especially since most Foci have no cooldown at all. I'd consider this a bug.

**Comment by Dayyer1** [comment]
I think it might be like that so the foci aren't used more than once during the cooldown.
Like if you had two weather foci on different wands. You could activate one, then activate the other one a few seconds later, which could mess with the game possibly. (I dunno I'm not a coder.)
Although if you're trying to use different foci, the cooldown thing would be annoying. The mod author said it was on purpose though.
It still seems like it should he edited, though.

**Comment by yorkeJohn** [comment]
It is not a bug. The foci can change the time of day. It has a 30 second cool down for a few reasons: changing the time of day is OP, and it would be SOOO annoying on servers if one obnoxious person could just change the time at will with no cool down whatsoever.
