### ISSUE TITLE
Grounded after update?

### ISSUE THREAD

**Issue by Crashcraft** [yorkeJohn/Tainted-Magic#50]
After searching for hours, I'm at a loss. After updating to r7.8 of Tainted Magic, I am unable to fly using any methods of doing so (angel ring from Extra Utilities, Robes of the Stratosphere from Thaumic Tinkerer), unless I'm in Creative mode. I honestly don't know how this happened or what to do, but if someone could just tell me what they need in order to fix this, I will gladly do what is needed. I REALLY don't want to have to uninstall Tainted Magic, as it is one of my favorite Thaumcraft Addons...

**Comment by yorkeJohn** [comment]
That might be caused by the new Flyte Charm... Let me take a look at it.

**Comment by yorkeJohn** [comment]
Fixed.
