### ISSUE TITLE
Crash With the Dark Matter Focus.

### ISSUE THREAD

**Issue by 63502** [yorkeJohn/Tainted-Magic#52]
Whenever I try to select my Dark Matter focus in my wand GUI, this happens. It only happens with the dark matter focus, not with any other tainted magic foci, or any other focus whatsoever.

[Crash Report](https://gist.github.com/63502/32650cb51827e316960021cf709f8c06)

My Dark matter focus is upgraded with potency 3, corrosive, and diffusion, if that helps at all.

**Comment by yorkeJohn** [comment]
See commit 6c7246f
This issue will be patched in the next release
