### ISSUE TITLE
Server-side Wand Focus upgrading

### ISSUE THREAD

**Issue by PokemonBlack1** [yorkeJohn/Tainted-Magic#53]
While upgrading foci, special addons like the Bloodlust for Mage's Mace and Diffusion/Insanity for Dark Matter don't work. This goes for the other upgrades added by this mod for their respective foci. This problem seems to be a server side issue, and the config for the server is an exact copy of the config from my client. There is no crashing happening, but clicking the green bar to start just makes the dud sound, like pressing a stone button. Request anything to help, and I'll see if I can get it.

**Comment by yorkeJohn** [comment]
Post the server log.

**Comment by PokemonBlack1** [comment]
http://pasted.co/a9d1d9d7

I turn it on, try it a few times, and turn it off. That's the entire log for it.

**Comment by yorkeJohn** [comment]
That is very strange. Literally no server log output.

**Comment by yorkeJohn** [comment]
Does this only happen serverside? Only on this one specific server? Does it happen with vanilla TC upgrades or only Tainted Magic upgrades? Are you on the latest build 7.82?

**Comment by PokemonBlack1** [comment]
Haven't tested on other servers. I will make a dummy server and test on there soon. Only with Tainted Magic upgrades, upgrades from Thaumatic Tinkerer are working just fine. And it is 7.82.

**Comment by PokemonBlack1** [comment]
After making the dummy server, I did NOT copy the config, so it generated new ones. Still the same. Wouldn't do the upgrades from TM.

**Comment by yorkeJohn** [comment]
Strange, did you try on client?

**Comment by PokemonBlack1** [comment]
It works on single player just fine.

**Comment by gayrt** [comment]
Can confirm. I’m on the most recent version of TM. On single player, the TM foci upgrades work just fine but on my server, they don’t queue up when I hit the green bar; just makes that sound when you’re selecting different options. All other wand foci upgrades work just fine.

**Comment by Natesky9** [comment]
Has this been fixed? It still won't upgrade for me, and we have the latest version. It only seems to be the modded foci upgrades
