### ISSUE TITLE
Mage's Mace on staffs not damaging mobs

### ISSUE THREAD

**Issue by IaeyanElyuex** [yorkeJohn/Tainted-Magic#56]
I recently got the idea to make a dedicated Mage's Mace staff. I finally figure it out, then I attach my Mage's Mace focus to it. It's not even doing slap damage. I'm clicking mobs with it, even right in their faces. No interaction whatsoever is occurring. The focus works when detached and put on my wand, so I'm not softcrashing.

What's the name of the log file I should post? There's a few in here.

**Comment by IaeyanElyuex** [comment]
Update on this. Wands are doing it, too. I have it upgraded with Potency V, and I'm using bone wand and staff.

It even started doing it with my silverwood/thaumium wand.

**Comment by yorkeJohn** [comment]
post any system logs... this is weird. The mace focus has been around a while, no one else has had problems with it.

**Comment by yorkeJohn** [comment]
also post a list of other mods you are using, forge version, thaumcraft version etc. Thanks.

**Comment by IaeyanElyuex** [comment]
Actually, I'm using a different staff, and it works now. I'm using the Primal Staff, and it works just fine. I don't get it. It has the Perditio regen, too. I thought that might have been it, but I haven't used the bone stuff in a long time, and the logs are probably overwritten by now.

**Comment by yorkeJohn** [comment]
The mace requires perditio vis to do anything so that was probably it.
