### ISSUE TITLE
Lumos replacing nodes

### ISSUE THREAD

**Issue by IaeyanElyuex** [yorkeJohn/Tainted-Magic#57]
I accidentally replaced one of my favorite nodes with a Lumos while experimenting to see if mobs could path through Lumos. I tried to place the Lumos sideways against a node in a stabilizer, and the Lumos just replaced the node! It was a rare node, too. Not every day you find Fames on a node that isn't a hungry one. I was able to track down the command to effectively replace it, but still. Argh.

**Comment by yorkeJohn** [comment]
Will look into this.
