### ISSUE TITLE
 New wand focus can not be changed

### ISSUE THREAD

**Issue by Dimpel75** [yorkeJohn/Tainted-Magic#58]
Hello I have now pulled your mod on my server but unfortunately it turns out I can not change their wandfokuse with the new enchantments that should bring her mod with. How could I fix this

**Comment by yorkeJohn** [comment]
I'm not sure I understand, can you give more information?

**Comment by Dimpel75** [comment]
hi first I can not speak English so I have google use hope the translation is good enough.
So my problem is the new Stabfokuse. I can see the new improvements that you can do with it in focus manipulator but not act. and improve. Example: Wall Focus Lumos I can thrift on it first spell glamor but the other two improvements I can see but not on the focus manipulator. Hope that my problem is now better described. Oh yeah, I use a mod package from Feed the Baest and got some extra mod. if this is important.

**Comment by Dimpel75** [comment]
mh .. habs times in single started there is there I can improve the focus so it must be because of my server only where fails with me unfortunately have not much idea with server settings

**Comment by haldor8** [comment]
I've got the same issue, I tried to upgrade the wand focus : lumos but when I tried to upgrade to glow pet or Lumos maxima, at the first upgrade only frugal works,  I haven't tried with the others wand focus

**Comment by IaeyanElyuex** [comment]
I can confirm this. I just tried to upgrade my Dark Matter focus with Sanity. The upgrade appears, I can click on it, but it won't let me start the upgrade process.

**Comment by yorkeJohn** [comment]
Thank you for the info, I will look into this more.

**Comment by yorkeJohn** [comment]
Was able to reproduce the issue. Was this happening prior to 7.82?

**Comment by Dimpel75** [comment]
I do not know that because I have tried her mod for the first time and have insterliert it with the last version

**Comment by IaeyanElyuex** [comment]
I have only ever used the latest version. My friend kind of forcibly dragged me into the modding scene. Most of my mods before Thaumcraft were pretty tame.

**Comment by yorkeJohn** [comment]
This is a very strange issue, there is no log output, and there was no major changes to foci in 7.82.

**Comment by gayrt** [comment]
Yeah I’m getting the same issue. Seems this has been going on for awhile, not sure how to work around it. Would appreciate an update in the near future.

**Comment by yorkeJohn** [comment]
Yeah fixed it. Fixing some other bugs. Update soon..

**Comment by gayrt** [comment]
Thanks man, this is an awesome addon so it’d be a shame if something as awesome as foci upgrades couldn’t work :/

**Comment by Dimpel75** [comment]
Hi first thank you for taking care of this mistake. But when your update seems to like to use it your focus is terrific. Well, definitely thank you
