### ISSUE TITLE
Thaumcraft 6 is released!

### ISSUE THREAD

**Issue by ghost** [yorkeJohn/Tainted-Magic#60]
so i dont know if this mod is dead but i really hope you will update this and i know it is a lot of affort especially because thaumcraft 6 is still in beta and nearly anithing changed but this addon is to good to simply dissapear in 1.7.10

**Comment by Kairi-lol** [comment]
Agreed!
I refuse to play thaumcraft without this mod!

**Comment by ghost** [comment]
i have to admit that thaumcraft six is VERY buggy
