### ISSUE TITLE
Mage's Mace kinda silly

### ISSUE THREAD

**Issue by Natesky9** [yorkeJohn/Tainted-Magic#62]
92 damage....

This completely breaks any semblance of balance in our pvp server, and actually had to be banned due to oneshotting literally anyone in any armor.

In versions past 1.9, this isn't *as* much of a problem, but in 1.7.10 where strength potions multiply damage, 96 damage is just way too high, and that's way too much damage for such a low cost + infinite durability.

I'd suggest the foci using .1 vis per damage dealt, and dealing slightly less damage

Tainted-Magic-r7.82
Minecraft 1.7.10

**Comment by yorkeJohn** [comment]
Config option was added for mage's mace and it costs vis.
