### ISSUE TITLE
Server-side Wand Focus Upgrading Explenation

### ISSUE THREAD

**Issue by 96Silver** [yorkeJohn/Tainted-Magic#63]
I know this has been fixed but I am unable to fix it in my files. I'm running a local forge server that my friends play on as well. Which file do I need to replace/add to make it work on the server? I had the forge version r7.82 installed. (focus upgrading works in single player)
I apologize for my stupidity and thank you in advance.

**Comment by Twilight2** [comment]
I got this problem too...

**Comment by EliManthey** [comment]
I'd like an answer to this as well
