### ISSUE TITLE
Void/Shadow Fortress Armor OP

### ISSUE THREAD

**Issue by vediis** [yorkeJohn/Tainted-Magic#65]
Would it be possible to push out a different version of the mod that nerfs void and shadow fortress armor? They're both so strong that they outstrip for example, the highest tier MineFantasy 2 armors and make balancing between several different mods very difficult. Right now our solution is to ban one piece of each set. Perhaps make these properties a configurable value?

**Comment by yorkeJohn** [comment]
yorkeJohn@c31c510
