### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by Gastr** [yorkeJohn/Tainted-Magic#67]
I tried to compile the newest version of Tainted magic. Client-side is ok and works but server-side crash everytime.

[crash-2020-03-28_16.22.21-server.txt](https://github.com/yorkeJohn/Tainted-Magic/files/4397359/crash-2020-03-28_16.22.21-server.txt)

[latest.log](https://github.com/yorkeJohn/Tainted-Magic/files/4397356/latest.log)

**Comment by yorkeJohn** [comment]
This version wasn’t released and was not bug tested. I’ll see if I can reproduce this issue once the version is complete.
