### ISSUE TITLE
Can you make the fortress blades enchantable?

### ISSUE THREAD

**Issue by Icylore** [yorkeJohn/Tainted-Magic#68]
Would be cool to have them compete with tinkers weapons and the edge of primordials which is enchantable.

**Comment by yorkeJohn** [comment]
Unfortunately enchantability is not a feature that will be added to the blades. The Fortress Blades are intentionally unenchantable, they have the Inscription system instead. It would be really hard to balance all of the special effects from the Inscriptions with enchantments, plus some enchantments might conflict with the Inscription effects.
