### ISSUE TITLE
Error on Server

### ISSUE THREAD

**Issue by Quark-Hell** [yorkeJohn/Tainted-Magic#69]
Hi.Recently I downloaded your repository and trying delete your nefr Shadow Fortress Armor.

**My steps:**
1)Downloaded your repositories
2)Downloaded Forge src for 1.7.10
3)Copied files from folder with Forge src and pate/replace in addon folder
4)Opened "ItemShadowFortressArmor.java" in Visual Studio and deleted your nerf
5)Saved changes
6)Opened cmd in addon folder
7)Wrote "gradlew build"
8)Find build in path "C:\...\Tainted-Magic\build\libs
9)Pasted build in folder with mods
It's over.

After I create local server and..it worked,nice! But after I push mod in my Server and I got this error:
[https://pastebin.com/QRF28cRU](url)

I hope on your help me. Thank you in advance.

P.S.Sorry for my English. I bad it know.

**Comment by yorkeJohn** [comment]
The code currently in the repository contains debug code that uses client side method calls that will crash a server. In progress code is never guranteed to work properly, you use it at your own risk. This crash will be resolved for deployment as debug code will be removed.

Thank you,
John
