### ISSUE TITLE
Tainted Storm rendering wierd...

### ISSUE THREAD

**Issue by Shahelion** [yorkeJohn/Tainted-Magic#7]
At the end of the animation, it seems to loop back to the start.

https://www.gyazo.com/05e542909ee454e99dc9fa7a7f371844

Also, unrelated, but I am currently unable to post on the MCF thread, and your picture on there is blank to me. Not sure what happened there.

**Comment by yorkeJohn** [comment]
The MFC issue seems to be on your end only. Also, I cannot view the video.

**Comment by Shahelion** [comment]
Edited the link. Does that one work?

**Comment by yorkeJohn** [comment]
Yes. That end animation is the popping animation. If you look in the texture file its an animated texture for the bubble, same as the fire focus animation.
