### ISSUE TITLE
Conflict With GraviSuite-1.7.10-2.0.3

### ISSUE THREAD

**Issue by TFCAliarcy** [yorkeJohn/Tainted-Magic#70]
Hello,
Just wanted to report that the latest update to tainted magic has caused issues with GraviSuite-1.7.10-2.0.3 causing the flight from the GraviChestPlate to not allow you to go up or down without using the boost key, fortunately this has not affected other jetpacks. Interestingly the bug can be avoided by equipping the flyte charm and source of vis from want/staff and will allow normal movement.

Also I want to say that I am thankful that you've updated the mod after all this time and fixed a number of bugs with the volcanic inscription radius causing a good amount of hilarity. I look forward to trying out the new features and changes in this update.

**Comment by yorkeJohn** [comment]
Unfortunately I cannot gurantee compatibility with other mods. Especially since GraviSuite is not open source, and I can't see what is going on on their side that could be causing the issue. I apologize for any inconvenience.

**Comment by yorkeJohn** [comment]
See #72 and 8e14119
The latest version (8.0.2) should fix this.
