### ISSUE TITLE
[Suggestion] Add a config toggle for the Lumos Focus' dynamic lighting

### ISSUE THREAD

**Issue by JohnsonJohnsonson** [yorkeJohn/Tainted-Magic#74]
It lags the game something fierce.

**Comment by yorkeJohn** [comment]
You are right. The code for the lumos dynamic lighting places / destroys invisible lightsource blocks every tick. This code was made a long time ago, and I didn't realize how laggy it is. This effect will be replaced with a night vision based effect in the next patch.
