### ISSUE TITLE
translation for mod

### ISSUE THREAD

**Issue by BetaSugar** [yorkeJohn/Tainted-Magic#78]
Where can I save the Russian localization for version 8.1.0 that I created? I have no experience with github

**Comment by BetaSugar** [comment]
oh, forget it. Looks like I've already been beaten...

**Comment by BetaSugar** [comment]
although it might still be useful to someone? compare translation quality or something...

**Comment by yorkeJohn** [comment]
You may contact @PingerHD about cross-referencing translation quality. Please open a new pull request with an updated translation if your cross refrence leads to any changes.
