### ISSUE TITLE
Ticking Entity Client Crash

### ISSUE THREAD

**Issue by Alaberti** [yorkeJohn/Tainted-Magic#8]
http://pastebin.com/H5h146iC

I'm not sure what causes this error or how to troubleshoot it, so here's what I have and hopefully it makes sense to you.

**Comment by yorkeJohn** [comment]
Update tainted magic. It was fixed in the newest version.

**Comment by Alaberti** [comment]
Is version 1.1.6.4 not the latest version?

**Comment by Alaberti** [comment]
I see now, the report is an old one, apologies.

**Comment by Alaberti** [comment]
http://pastebin.com/cVpyNTqy This is the correct crash log, from version 1.1.6.4.

**Comment by yorkeJohn** [comment]
It is a problem with the class that updates the attack damage for the Mage's Mace focus. not sure what though.

**Comment by Alaberti** [comment]
The ticking player does have one; are there any tests you'd like me to have them try?

**Comment by yorkeJohn** [comment]
I have (potentially) fixed this issue, the fix will be in the next patch.

**Comment by Eufranio** [comment]
Next patch... ?
