### ISSUE TITLE
Allow downloading from third-party launchers

### ISSUE THREAD

**Issue by ExistingExpert** [yorkeJohn/Tainted-Magic#84]
May I ask why this mod was blocked for third-party launchers? I can only assume it was so that CF's download statistics are not messed up. Can this mod be unblocked? Many people don't, or straight up can't use Overwolf's launcher due to privacy concerns, and the fact that it is not available for linux (it only supports WOW). Due to this people have to manually download this mod everytime from the website (which, imo, is pretty meh) and forgo automatic updates for good. If this mod is unblocked, GTNH will be able to be downloaded from third-party launchers without needing to manually download mods.

**Comment by yorkeJohn** [comment]
Where are you seeing that it is blocked from 3rd party launchers? I don’t recall making this a rule, and I have definitely seen it up for download from 3rd party sources.

**Comment by ExistingExpert** [comment]
![image](https://user-images.githubusercontent.com/71560815/204836232-9d5ef5d1-3fc9-49ae-a742-a3eff5f6cd8f.png)
Prismlauncher while trying to install Gregtech

**Comment by yorkeJohn** [comment]
I do not know why this is happening, I did not do anything to mark the mod as unavailable for third party launchers.
Also it is worth noting, why are you using an outdated version of the mod? Have you tried using the latest version?

**Comment by ExistingExpert** [comment]
I am downloading [GT:NH modpack](https://www.curseforge.com/minecraft/modpacks/gt-new-horizons) from curseforge, which uses this version. But I don't believe that the curseforge setting for blocking third-party downloads is version specific (may be wrong though).

**Comment by yorkeJohn** [comment]
I see, I didn’t realize that this setting existed. It must be new since CurseForge was acquired by Overwolf… Try now.

**Comment by ExistingExpert** [comment]
It works now!
![image](https://user-images.githubusercontent.com/71560815/205201420-1fbb6d78-1277-456d-8b47-67a2081f712a.png)
